---
# VM Configuration
vm:
  # 64-bit CentOS
  box: 'centos65x64'
  box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box'
  # # 32-bit CentOS
  # box: 'centos65i386'
  # box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/centos-65-i386-virtualbox-puppet.box'
  # # 64-bit Ubuntu
  # box: 'precise64'
  # box_url: 'http://files.vagrantup.com/precise64.box'
  # # 32-bit Ubuntu
  # box: 'precise32'
  # box_url: 'http://files.vagrantup.com/precise32.box'
  memory: '1000'
  swap: '500'
  ssh_port: 2222
  ssh_port_auto_correct: false
  web_port: 8080
  web_port_auto_correct: false
# Autotool Configuration
autotool::build_doc: true
autotool::autolib::url: 'git://autolat.imn.htwk-leipzig.de/git/autolib'
autotool::autolib::branch: 'release'
autotool::tool::url: 'git://autolat.imn.htwk-leipzig.de/git/tool'
autotool::tool::branch: 'classic-via-rpc'
autotool::database::school_name: 'school'
autotool::database::school_mail_suffix: 'localhost'
autotool::database::minister_matrikel_number: '0'
autotool::database::minister_email: 'vagrant@localhost'
autotool::database::minister_familyname: 'Mustermann'
autotool::database::minister_name: 'Max'
autotool::database::minister_password: 'foobar'
# Haskell Configuration
haskell::ghc::version: '7.6.3'
haskell::cabal::version: '1.18.1.3'
haskell::cabal_install::version: '1.18.0.2'
haskell::maxruns: 10
