---
# VM Configuration
vm:
  # 64-bit CentOS
  box: 'centos65x64'
  box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box'
  # # 32-bit CentOS
  # box: 'centos65i386'
  # box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/centos-65-i386-virtualbox-puppet.box'
  # # 64-bit Ubuntu
  # box: 'precise64'
  # box_url: 'http://files.vagrantup.com/precise64.box'
  # # 32-bit Ubuntu
  # box: 'precise32'
  # box_url: 'http://files.vagrantup.com/precise32.box'
  memory: '2000'
  swap: '1000'
  ssh_port: 2222
  ssh_port_auto_correct: false
  web_port: 8080
  web_port_auto_correct: false
# Autotool Configuration
autotool::build_doc: true
autotool::enable_highscore: true
autotool::autolib::url: 'git://autolat.imn.htwk-leipzig.de/git/autolib'
autotool::autolib::branch: 'for-ghc-7.8'
autotool::tool::url: 'https://github.com/marcellussiegburg/autotool.git'
autotool::tool::branch: 'for-ghc-7.8'
autotool::database::school_name: 'school'
autotool::database::school_mail_suffix: 'localhost'
autotool::database::minister_matrikel_number: '0'
autotool::database::minister_email: 'vagrant@localhost'
autotool::database::minister_familyname: 'Mustermann'
autotool::database::minister_name: 'Max'
autotool::database::minister_password: 'foobar'
# Haskell Configuration
haskell::ghc::version: '7.8.2'
haskell::cabal::version: '1.20.0.1'
haskell::cabal_install::version: '1.20.0.2'
haskell::maxruns: 10
haskell::packages:
 - haskell-src-exts-1.15.0.1
 - text-0.11.3.1
 - mtl-2.1.3.1
haskell::git_packages:
 'cgi':
   url: 'https://github.com/jhenahan/haskell-cgi'
