---
# VM Configuration
vm:
  # 64-bit CentOS
  box: 'centos65x64'
  box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box'
  # # 32-bit CentOS
  # box: 'centos65i386'
  # box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/centos-65-i386-virtualbox-puppet.box'
  # # 64-bit Ubuntu
  # box: 'precise64'
  # box_url: 'http://files.vagrantup.com/precise64.box'
  # # 32-bit Ubuntu
  # box: 'precise32'
  # box_url: 'http://files.vagrantup.com/precise32.box'
  memory: '2000'
  swap: '1000'
  ssh_port: 2222
  ssh_port_auto_correct: false
  web_port: 8080
  web_port_auto_correct: false
  yesod_port: 3333
  yesod_port_auto_correct: false
# Autotool Configuration
autotool::build_doc: true
autotool::enable_highscore: true
autotool::sandbox: true
autotool::install_path: '/home/vagrant/tool/yesod'
autotool::sources::autolib_url: 'git://autolat.imn.htwk-leipzig.de/git/autolib'
autotool::sources::autolib_branch: 'for-ghc-7.8'
autotool::sources::tool_url: 'https://github.com/marcellussiegburg/autotool.git'
autotool::sources::tool_branch: 'yesod'
autotool::database::school_name: 'school'
autotool::database::school_mail_suffix: 'localhost'
autotool::database::minister_matrikel_number: '0'
autotool::database::minister_email: 'vagrant@localhost'
autotool::database::minister_familyname: 'Mustermann'
autotool::database::minister_name: 'Max'
autotool::database::minister_password: 'foobar'
# Haskell Configuration
haskell::wget_param: '--no-check-certificate'
haskell::ghc::version: '7.8.3'
haskell::cabal::version: '1.20.0.2'
haskell::cabal_install::version: '1.20.0.3'
haskell::maxruns: 10
haskell::haddock_version: '2.15.0.2'
haskell::bins:
 - hlint
 - yesod-bin
haskell::packages:
 - blaze-html-0.7.1.0
 - haskell-src-exts-1.16.0.1
haskell::git_packages:
